### PR TITLE
capture header and query parameters

### PR DESCRIPTION
**Pull request by bewest**
Very nice library, but I need some changes to make it work.  Query parameters were previously formatted as "[object object]". This patch uses qs library to correctly urlencode any remaining query string values.

Correctly capture headers.  There is no documented `headers.common` object, it's a plain object with keys and values.  Before this, no headers were recorded.

### CODE REVIEW

**Comment by BeataKr** [comment]
Can you please check does 0.5.0 resole your expectations according to the headers?

**Comment by bewest** [comment]
https://github.com/BeataKr/axios-har-tracker/pull/9 Looks good, thank you.  Looks like this will capture request bodies as well?  Does HAR output use `content` or `postData`, or does it depend on HTTP method?
Also note some package/dependency management re, jest, typescript, etc.

**Comment by BeataKr** [comment]
> #9 Looks good, thank you. Looks like this will capture request bodies as well? Does HAR output use `content` or `postData`, or does it depend on HTTP method? Also note some package/dependency management re, jest, typescript, etc.

Changed things https://github.com/BeataKr/axios-har-tracker/pull/9/files#diff-bf2833959cfb84b3c8f83aca5efab3d7e914c9a8ab7be8b9c959d8613d9d0fef

**Comment by BeataKr** [comment]
0.5.1 contains raised packs https://github.com/BeataKr/axios-har-tracker/pull/10/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by BeataKr** [comment]
in the next step I'll try to raise `axios`

**Pull request closed without merging**
